"""
Auto-generated Data Pipeline: Sensor Data
Description: Process the uploaded data with the following transformations: deduplicate, normalize, filter. Based on analysis, handle 1.25% null values and 1 duplicates.
Generated by: Automatic Data Pipeline Generator
"""

import pandas as pd
import hashlib
import json
import structlog
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any

# Configure logging
structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.stdlib.BoundLogger,
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
)

logger = structlog.get_logger()


class Sensor DataPipeline:
    """
    Data pipeline for Process the uploaded data with the following transformations: deduplicate, normalize, filter. Based on analysis, handle 1.25% null values and 1 duplicates..
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        """Initialize the pipeline with optional configuration."""
        self.config = config or {}
        self.state_file = Path("pipeline_state.json")
        self.metrics = {
            "records_processed": 0,
            "records_failed": 0,
            "start_time": None,
            "end_time": None
        }
        logger.info("Pipeline initialized", pipeline="Sensor Data")
    
    def _compute_hash(self, data: pd.DataFrame) -> str:
        """Compute hash for idempotency checking."""
        return hashlib.md5(pd.util.hash_pandas_object(data).values.tobytes()).hexdigest()
    
    def _load_state(self) -> Dict:
        """Load pipeline state for idempotent execution."""
        if self.state_file.exists():
            with open(self.state_file) as f:
                return json.load(f)
        return {"last_hash": None, "last_run": None}
    
    def _save_state(self, data_hash: str):
        """Save pipeline state."""
        state = {
            "last_hash": data_hash,
            "last_run": datetime.now().isoformat()
        }
        with open(self.state_file, 'w') as f:
            json.dump(state, f)
    
    def extract(self, source_path: str) -> pd.DataFrame:
        """Extract data from source."""
        logger.info("Extracting data", source=source_path)
        try:
            source_format = "csv"
            
            if source_format == "csv":
                df = pd.read_csv(source_path)
            elif source_format == "json":
                df = pd.read_json(source_path)
            elif source_format in ["excel", "xlsx", "xls"]:
                df = pd.read_excel(source_path)
            elif source_format == "parquet":
                df = pd.read_parquet(source_path)
            else:
                df = pd.read_csv(source_path)  # default to CSV
            
            logger.info("Data extracted", rows=len(df), columns=len(df.columns))
            return df
            
        except Exception as e:
            logger.error("Extraction failed", error=str(e))
            raise
    
    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        """Apply transformations to the data."""
        logger.info("Starting transformations", input_rows=len(df))
        
        try:

            # Step 1: Handle missing values
            logger.info("Applying transformation", step=1, type="validate")

            # Remove rows with all null values
            df = df.dropna(how='all')
            # Fill remaining nulls with appropriate defaults
            for col in df.select_dtypes(include=['number']).columns:
                df[col] = df[col].fillna(df[col].median())
            for col in df.select_dtypes(include=['object']).columns:
                df[col] = df[col].fillna('UNKNOWN')

            # Step 2: Filter data based on conditions
            logger.info("Applying transformation", step=2, type="filter")

            # Apply filtering (customize conditions as needed)
            # TODO: add actual filter conditions here
            # df = df[df['column_name'] > threshold]
            pass

            # Step 3: Normalize data values
            logger.info("Applying transformation", step=3, type="normalize")

            # Normalize numeric columns
            numeric_cols = df.select_dtypes(include=['number']).columns
            for col in numeric_cols:
                min_val = df[col].min()
                max_val = df[col].max()
                if max_val > min_val:
                    df[col] = (df[col] - min_val) / (max_val - min_val)

            # Step 4: Remove duplicates
            logger.info("Applying transformation", step=4, type="deduplicate")

            # Remove duplicate rows
            initial_count = len(df)
            df = df.drop_duplicates()
            logger.info("Deduplication complete", removed=initial_count - len(df))

            self.metrics["records_processed"] = len(df)
            logger.info("Transformations complete", output_rows=len(df))
            return df
            
        except Exception as e:
            logger.error("Transformation failed", error=str(e))
            raise
    
    def load(self, df: pd.DataFrame, destination_path: str):
        """Load data to destination."""
        logger.info("Loading data", destination=destination_path)
        
        try:
            dest_format = "csv"
            
            if dest_format == "csv":
                df.to_csv(destination_path, index=False)
            elif dest_format == "json":
                df.to_json(destination_path, orient='records', indent=2)
            elif dest_format == "parquet":
                df.to_parquet(destination_path, index=False)
            elif dest_format in ["excel", "xlsx"]:
                df.to_excel(destination_path, index=False)
            else:
                df.to_csv(destination_path, index=False)
            
            logger.info("Data loaded successfully", rows=len(df))
            
        except Exception as e:
            logger.error("Loading failed", error=str(e))
            raise
    
    def run(self, source_path: str, destination_path: str, force: bool = False) -> Dict[str, Any]:
        """
        Execute the complete ETL pipeline.
        
        Args:
            source_path: Path to source data
            destination_path: Path for output data
            force: Force execution even if data unchanged
            
        Returns:
            Dictionary with execution metrics
        """
        self.metrics["start_time"] = datetime.now().isoformat()
        logger.info("Pipeline execution started", 
                   source=source_path, 
                   destination=destination_path)
        
        try:
            # Extract
            df = self.extract(source_path)
            
            # Check for idempotency
            data_hash = self._compute_hash(df)
            state = self._load_state()
            
            if not force and state["last_hash"] == data_hash:
                logger.info("Data unchanged, skipping execution")
                return {"status": "skipped", "reason": "data_unchanged"}
            
            # Transform
            df = self.transform(df)
            
            # Load
            self.load(df, destination_path)
            
            # Save state
            self._save_state(data_hash)
            
            self.metrics["end_time"] = datetime.now().isoformat()
            self.metrics["status"] = "success"
            
            logger.info("Pipeline execution completed", metrics=self.metrics)
            return self.metrics
            
        except Exception as e:
            self.metrics["end_time"] = datetime.now().isoformat()
            self.metrics["status"] = "failed"
            self.metrics["error"] = str(e)
            logger.error("Pipeline execution failed", error=str(e))
            raise


def main():
    """Main entry point for the pipeline."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Sensor Data")
    parser.add_argument("--source", "-s", required=True, help="Source data path")
    parser.add_argument("--destination", "-d", required=True, help="Destination path")
    parser.add_argument("--force", "-f", action="store_true", help="Force execution")
    
    args = parser.parse_args()
    
    pipeline = Sensor DataPipeline()
    result = pipeline.run(args.source, args.destination, args.force)
    
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
